In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 21, 22, 23, 24

***Opening And ELimination Stages***

In [ ]:
def extract_link_text(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    
    h1_tag = soup.find('h1', {'class': 'firstHeading'})
    if h1_tag:
        return h1_tag.get_text(strip=True)
    return None

url = "https://liquipedia.net/counterstrike/PGL/2021/Stockholm"
response = requests.get(url)

if response.status_code == 200:     #if greater than 200 cannot extract
    soup = BeautifulSoup(response.content, "html.parser")
    
    tables = soup.find_all("table", class_="wikitable wikitable-bordered wikitable-striped swisstable")
    # tables = soup.find_all("table", class_="table table-bordered table-striped swisstable")#inspect element second table

    count = 0
    for table in tables:
        headers = [header.text.strip() for header in table.find('tr')]
        
        data = []
        rows = table.find_all("tr")

        for row in rows:
            cells = []
            for cell in row.find_all(['td', 'th']):
                link = cell.find('a')
                if link:
                    url = link.get('href')
                    if url:
                        if not url.startswith('http'):
                            url = 'https://liquipedia.net' + url
                        link_text = extract_link_text(url)
                        cells.append(link_text)
                else:
                    cells.append(cell.get_text(strip=True))
            
            if cells:  
                data.append(cells)
        
        data.pop(0) # Removing headers
        
        if data:
            df = pd.DataFrame(data, columns=headers)
            df.drop(['BU','#'], axis=1, inplace=True)
            if count == 0:
                df_o = df
            else:
                df_e = df
            
            count += 1
# df_e

***Playoff Stages***

**2024**

In [109]:
data = {
    'Team': ['Team Spirit', 'FaZe Clan', 'Team Vitality', 'Cloud9', 'Eternal Fire', 'Natus Vincere', 'G2 Esports', 'MOUZ'],
    'Matches' : ['0-1','2-1','1-1','0-1','0-1','3-0','1-1','0-1'],
    'Rounds': ['40-45','101-96','54-41','10-26','22-29','93-84','63-51','15-26'],
    'RD' : [-5,5,13,-16,-7,9,12,-11],
    'Round 1' : ['FaZe Clan','Team Spirit','Cloud9','Team Vitality','Natus Vincere','Eternal Fire','MOUZ','G2 Esports'],
    'Round 2': ['','Team Vitality','FaZe Clan','','','G2 Esports','Natus Vincere',''],
    'Round 3' : ['','Natus Vincere','','','','FaZe Clan','',''],
    'Round 4' : ['','','','','','','',''],
    'Round 5' : ['','','','','','','','']
}
df_p4 = pd.DataFrame(data)

df_p4[['Wins', 'Losses']] = df_p4['Matches'].str.split('-', expand=True).astype(int)
df_sorted = df_p4.sort_values(by=['Wins', 'Losses'], ascending=[False, True])
df_p4 = df_sorted.drop(columns=['Wins', 'Losses']).reset_index(drop=True)
df_p4

,Team,Matches,Rounds,RD,Round 1,Round 2,Round 3,Round 4,Round 5
0,Natus Vincere,3-0,93-84,9,Eternal Fire,G2 Esports,FaZe Clan,,
1,FaZe Clan,2-1,101-96,5,Team Spirit,Team Vitality,Natus Vincere,,
2,Team Vitality,1-1,54-41,13,Cloud9,FaZe Clan,,,
3,G2 Esports,1-1,63-51,12,MOUZ,Natus Vincere,,,
4,Team Spirit,0-1,40-45,-5,FaZe Clan,,,,
5,Cloud9,0-1,10-26,-16,Team Vitality,,,,
6,Eternal Fire,0-1,22-29,-7,Natus Vincere,,,,
7,MOUZ,0-1,15-26,-11,G2 Esports,,,,

**2023**

In [116]:
data = {
    'Team': ['Heroic', 'FaZe Clan', 'GamerLegion', 'Monte', 'Team Liquid', 'Apeks', 'Into The Breach', 'Team Vitality'],
    'Matches' : ['1-1','0-1','2-1','0-1','0-1','1-1','0-1','3-0'],
    'Rounds': ['80-81','36-44','96-81','13-32','21-32','58-53','23-32','96-68'],
    'RD' : [-1,-8,15,-19,-11,5,-9,28],
    'Round 1' : ['FaZe Clan','Heroic','Monte','GamerLegion','Apeks','Team Liquid','Team Vitality','Into The Breach'],
    'Round 2': ['GamerLegion','','Heroic','','','Team Vitality','','Apeks'],
    'Round 3' : ['','','Team Vitality','','','','','GamerLegion'],
    'Round 4' : ['','','','','','','',''],
    'Round 5' : ['','','','','','','','']
}
df_p3 = pd.DataFrame(data)

df_p3[['Wins', 'Losses']] = df_p3['Matches'].str.split('-', expand=True).astype(int)
df_sorted = df_p3.sort_values(by=['Wins', 'Losses'], ascending=[False, True])
df_p3 = df_sorted.drop(columns=['Wins', 'Losses']).reset_index(drop=True)
df_p3

,Team,Matches,Rounds,RD,Round 1,Round 2,Round 3,Round 4,Round 5
0,Team Vitality,3-0,96-68,28,Into The Breach,Apeks,GamerLegion,,
1,GamerLegion,2-1,96-81,15,Monte,Heroic,Team Vitality,,
2,Heroic,1-1,80-81,-1,FaZe Clan,GamerLegion,,,
3,Apeks,1-1,58-53,5,Team Liquid,Team Vitality,,,
4,FaZe Clan,0-1,36-44,-8,Heroic,,,,
5,Monte,0-1,13-32,-19,GamerLegion,,,,
6,Team Liquid,0-1,21-32,-11,Apeks,,,,
7,Into The Breach,0-1,23-32,-9,Team Vitality,,,,

**2022**

In [121]:
data = {
    'Team': ['Team Spirit', 'FURIA Esports', 'FaZe Clan', 'Ninjas in Pyjamas', 'ENCE', 'CPH Flames', 'Heroic', 'Natus Vincere'],
    'Matches' : ['1-1','0-1','3-0','0-1','1-1','0-1','0-1','2-1'],
    'Rounds': ['72-61','20-32','121-96','34-45','51-54','22-32','38-42','100-92'],
    'RD' : [11,-12,25,-11,-3,-10,-4,8],
    'Round 1' : ['FURIA Esports','Team Spirit','Ninjas in Pyjamas','FaZe Clan','CPH Flames','ENCE','Natus Vincere','Heroic'],
    'Round 2': ['FaZe Clan','','Team Spirit','','Natus Vincere','','','ENCE'],
    'Round 3' : ['','','Natus Vincere','','','','','FaZe Clan'],
    'Round 4' : ['','','','','','','',''],
    'Round 5' : ['','','','','','','','']
}
df_p2 = pd.DataFrame(data)

df_p2[['Wins', 'Losses']] = df_p2['Matches'].str.split('-', expand=True).astype(int)
df_sorted = df_p2.sort_values(by=['Wins', 'Losses'], ascending=[False, True])
df_p2 = df_sorted.drop(columns=['Wins', 'Losses']).reset_index(drop=True)
df_p2

,Team,Matches,Rounds,RD,Round 1,Round 2,Round 3,Round 4,Round 5
0,FaZe Clan,3-0,121-96,25,Ninjas in Pyjamas,Team Spirit,Natus Vincere,,
1,Natus Vincere,2-1,100-92,8,Heroic,ENCE,FaZe Clan,,
2,Team Spirit,1-1,72-61,11,FURIA Esports,FaZe Clan,,,
3,ENCE,1-1,51-54,-3,CPH Flames,Natus Vincere,,,
4,FURIA Esports,0-1,20-32,-12,Team Spirit,,,,
5,Ninjas in Pyjamas,0-1,34-45,-11,FaZe Clan,,,,
6,CPH Flames,0-1,22-32,-10,ENCE,,,,
7,Heroic,0-1,38-42,-4,Natus Vincere,,,,

**2021**

In [125]:
data = {
    'Team': ['Natus Vincere', 'Team Vitality', 'FURIA Esports', 'Gambit Esports', 'Heroic', 'Virtus.pro', 'Ninjas in Pyjamas', 'G2 Esports'],
    'Matches' : ['3-0','0-1','0-1','1-1','1-1','0-1','0-1','2-1'],
    'Rounds': ['102-65','24-32','27-35','46-59','86-85','38-45','22-32','109-101'],
    'RD' : [37,-8,-8,-13,1,-7,-10,8],
    'Round 1' : ['Team Vitality','Natus Vincere','Gambit Esports','FURIA Esports','Virtus.pro','Heroic','G2 Esports','Ninjas in Pyjamas'],
    'Round 2': ['Gambit Esports','','','Natus Vincere','G2 Esports','','','Heroic'],
    'Round 3' : ['G2 Esports','','','','','','','Natus Vincere'],
    'Round 4' : ['','','','','','','',''],
    'Round 5' : ['','','','','','','','']
}
df_p1 = pd.DataFrame(data)

df_p1[['Wins', 'Losses']] = df_p1['Matches'].str.split('-', expand=True).astype(int)
df_sorted = df_p1.sort_values(by=['Wins', 'Losses'], ascending=[False, True])
df_p1 = df_sorted.drop(columns=['Wins', 'Losses']).reset_index(drop=True)
df_p1

,Team,Matches,Rounds,RD,Round 1,Round 2,Round 3,Round 4,Round 5
0,Natus Vincere,3-0,102-65,37,Team Vitality,Gambit Esports,G2 Esports,,
1,G2 Esports,2-1,109-101,8,Ninjas in Pyjamas,Heroic,Natus Vincere,,
2,Gambit Esports,1-1,46-59,-13,FURIA Esports,Natus Vincere,,,
3,Heroic,1-1,86-85,1,Virtus.pro,G2 Esports,,,
4,Team Vitality,0-1,24-32,-8,Natus Vincere,,,,
5,FURIA Esports,0-1,27-35,-8,Gambit Esports,,,,
6,Virtus.pro,0-1,38-45,-7,Heroic,,,,
7,Ninjas in Pyjamas,0-1,22-32,-10,G2 Esports,,,,

***2024 Data Frame***

In [ ]:
# df_24 = pd.concat([df_o, df_e, df_p4], keys=['Opening Stage', 'Elimination Stage', 'Playoff Stage'])
# path = r"C:\Languages\python\PFAI\Project\2024.csv"
# df_24.to_csv(path)
# df_24

                                    Team Matches   Rounds   RD  \
Opening Stage     0               HEROIC     3-0    58-40  +18
                  1               Cloud9     3-0    58-46  +12
                  2         Eternal Fire     3-1    77-63  +14
                  3             ECSTATIC     3-1    72-57  +15
                  4          paiN Gaming     3-1    54-41  +13
                  5     Imperial Esports     3-2  113-105   +8
                  6          The MongolZ     3-2   102-80  +22
                  7        FURIA Esports     3-2   100-75  +25
                  8                  SAW     2-3    83-97  -14
                  9               Legacy     2-3    71-79   -8
                  10         GamerLegion     2-3    88-93   -5
                  11  Lynn Vision Gaming     1-3    40-61  -21
                  12                ENCE     1-3    55-73  -18
                  13               Apeks     1-3    45-65  -20
                  14       AMKAL ESPORTS     0-3    46-63  -17
                  15                 KOI     0-3    31-55  -24
Elimination Stage 0          Team Spirit     3-0    65-41  +24
                  1                 MOUZ     3-0    52-25  +27
                  2         Eternal Fire     3-1    69-50  +19
                  3               Cloud9     3-1    73-49  +24
                  4        Team Vitality     3-1    75-70   +5
                  5        Natus Vincere     3-2  108-119  -11
                  6           G2 Esports     3-2   110-90  +20
                  7            FaZe Clan     3-2    84-74  +10
                  8    Complexity Gaming     2-3   86-117  -31
                  9           Virtus.pro     2-3   91-100   -9
                  10         paiN Gaming     2-3  107-109   -2
                  11    Imperial Esports     1-3    53-66  -13
                  12            ECSTATIC     1-3    82-93  -11
                  13              HEROIC     1-3    51-68  -17
                  14         The MongolZ     0-3    61-70   -9
                  15       FURIA Esports     0-3    40-66  -26
Playoff Stage     0        Natus Vincere     3-0    93-84    9
                  1            FaZe Clan     2-1   101-96    5
                  2        Team Vitality     1-1    54-41   13
                  3           G2 Esports     1-1    63-51   12
                  4          Team Spirit     0-1    40-45   -5
                  5               Cloud9     0-1    10-26  -16
                  6         Eternal Fire     0-1    22-29   -7
                  7                 MOUZ     0-1    15-26  -11

                                 Round 1             Round 2  \
Opening Stage     0   Lynn Vision Gaming    Imperial Esports
                  1             ECSTATIC              Legacy
                  2          The MongolZ         paiN Gaming
                  3               Cloud9         The MongolZ
                  4                Apeks        Eternal Fire
                  5                 ENCE              HEROIC
                  6         Eternal Fire            ECSTATIC
                  7               Legacy  Lynn Vision Gaming
                  8                  KOI         GamerLegion
                  9        FURIA Esports              Cloud9
                  10       AMKAL ESPORTS                 SAW
                  11              HEROIC       FURIA Esports
                  12    Imperial Esports                 KOI
                  13         paiN Gaming       AMKAL ESPORTS
                  14         GamerLegion               Apeks
                  15                 SAW                ENCE
Elimination Stage 0               Cloud9    Imperial Esports
                  1             ECSTATIC        Eternal Fire
                  2        Team Vitality                MOUZ
                  3          Team Spirit            ECSTATIC
                  4         Eternal Fire         The MongolZ
                  5          The MongolZ          G2 Esports
                  6        FURIA Esports       Natus Vincere
                  7               HEROIC       FURIA Esports
                  8          paiN Gaming              HEROIC
                  9     Imperial Esports         paiN Gaming
                  10   Complexity Gaming          Virtus.pro
                  11          Virtus.pro         Team Spirit
                  12                MOUZ              Cloud9
                  13           FaZe Clan   Complexity Gaming
                  14       Natus Vincere       Team Vitality
                  15          G2 Esports           FaZe Clan
Playoff Stage     0         Eternal Fire          G2 Esports
                  1          Team Spirit       Team Vitality
                  2               Cloud9           FaZe Clan
                  3                 MOUZ       Natus Vincere
                  4            FaZe Clan
                  5        Team Vitality
                  6        Natus Vincere
                  7           G2 Esports

                                 Round 3             Round 4  \
Opening Stage     0         Eternal Fire
                  1                  SAW
                  2               HEROIC         GamerLegion
                  3   Lynn Vision Gaming    Imperial Esports
                  4                 ENCE                 SAW
                  5                Apeks            ECSTATIC
                  6        AMKAL ESPORTS  Lynn Vision Gaming
                  7                  KOI                ENCE
                  8               Cloud9         paiN Gaming
                  9          GamerLegion               Apeks
                  10              Legacy        Eternal Fire
                  11            ECSTATIC         The MongolZ
                  12         paiN Gaming       FURIA Esports
                  13    Imperial Esports              Legacy
                  14         The MongolZ
                  15       FURIA Esports
Elimination Stage 0        Natus Vincere
                  1    Complexity Gaming
                  2            FaZe Clan          Virtus.pro
                  3           G2 Esports       Natus Vincere
                  4     Imperial Esports   Complexity Gaming
                  5          Team Spirit              Cloud9
                  6               Cloud9            ECSTATIC
                  7         Eternal Fire    Imperial Esports
                  8                 MOUZ       Team Vitality
                  9               HEROIC        Eternal Fire
                  10         The MongolZ              HEROIC
                  11       Team Vitality           FaZe Clan
                  12       FURIA Esports          G2 Esports
                  13          Virtus.pro         paiN Gaming
                  14         paiN Gaming
                  15            ECSTATIC
Playoff Stage     0            FaZe Clan
                  1        Natus Vincere
                  2
                  3
                  4
                  5
                  6
                  7

                                Round 5
Opening Stage     0
                  1
                  2
                  3
                  4
                  5         GamerLegion
                  6              Legacy
                  7                 SAW
                  8       FURIA Esports
                  9         The MongolZ
                  10   Imperial Esports
                  11
                  12
                  13
                  14
                  15
Elimination Stage 0
                  1
                  2
                  3
                  4
                  5         paiN Gaming
                  6          Virtus.pro
                  7   Complexity Gaming
                  8           FaZe Clan
                  9          G2 Esports
                  10      Natus Vincere
                  11
                  12
                  13
                  14
                  15
Playoff Stage     0
                  1
                  2
                  3
                  4
                  5
                  6
                  7

***2023 Data Frame***

In [ ]:
# df_23 = pd.concat([df_o, df_e, df_p3], keys=['Opening Stage', 'Elimination Stage', 'Playoff Stage'])
# path = r"C:\Languages\python\PFAI\Project\2023.csv"
# df_23.to_csv(path)
# df_23

                                   Team Matches   Rounds   RD  \
Opening Stage     0                ENCE     3-0    76-52  +24
                  1          G2 Esports     3-0    64-34  +30
                  2               Apeks     3-1    91-80  +11
                  3           FaZe Clan     3-1   101-93   +8
                  4   Ninjas in Pyjamas     3-1    76-65  +11
                  5               Monte     3-2   110-92  +18
                  6         Team Liquid     3-2  133-107  +26
                  7         GamerLegion     3-2  126-110  +16
                  8       FORZE Esports     2-3   94-100   -6
                  9    Grayhound Gaming     2-3   73-104  -31
                  10        paiN Gaming     2-3  107-109   -2
                  11  Complexity Gaming     1-3    43-75  -32
                  12        The MongolZ     1-3    62-75  -13
                  13                 OG     1-3    75-86  -11
                  14               MOUZ     0-3    37-64  -27
                  15              Fluxo     0-3    53-75  -22
Elimination Stage 0              HEROIC     3-0    75-56  +19
                  1       Team Vitality     3-0    64-49  +15
                  2         Team Liquid     3-1   106-86  +20
                  3               Monte     3-1    90-70  +20
                  4         GamerLegion     3-1    74-55  +19
                  5               Apeks     3-2    95-97   -2
                  6     Into The Breach     3-2   112-98  +14
                  7           FaZe Clan     3-2  140-137   +3
                  8       Natus Vincere     2-3   94-118  -24
                  9              Fnatic     2-3  120-133  -13
                  10  Ninjas in Pyjamas     2-3   101-95   +6
                  11               ENCE     1-3    53-73  -20
                  12    Bad News Eagles     1-3    78-83   -5
                  13         G2 Esports     1-3   101-95   +6
                  14               9INE     0-3    40-64  -24
                  15      FURIA Esports     0-3    30-64  -34
Playoff Stage     0       Team Vitality     3-0    96-68   28
                  1         GamerLegion     2-1    96-81   15
                  2              Heroic     1-1    80-81   -1
                  3               Apeks     1-1    58-53    5
                  4           FaZe Clan     0-1    36-44   -8
                  5               Monte     0-1    13-32  -19
                  6         Team Liquid     0-1    21-32  -11
                  7     Into The Breach     0-1    23-32   -9

                                Round 1            Round 2            Round 3  \
Opening Stage     0                  OG  Ninjas in Pyjamas          FaZe Clan
                  1         The MongolZ  Complexity Gaming              Apeks
                  2         Team Liquid   Grayhound Gaming         G2 Esports
                  3               Monte        paiN Gaming               ENCE
                  4                MOUZ               ENCE                 OG
                  5           FaZe Clan              Fluxo      FORZE Esports
                  6               Apeks      FORZE Esports              Fluxo
                  7   Complexity Gaming        The MongolZ               MOUZ
                  8    Grayhound Gaming        Team Liquid              Monte
                  9       FORZE Esports              Apeks        The MongolZ
                  10              Fluxo          FaZe Clan  Complexity Gaming
                  11        GamerLegion         G2 Esports        paiN Gaming
                  12         G2 Esports        GamerLegion   Grayhound Gaming
                  13               ENCE               MOUZ  Ninjas in Pyjamas
                  14  Ninjas in Pyjamas                 OG        GamerLegion
                  15        paiN Gaming              Monte        Team Liquid
Elimination Stage 0           FaZe Clan              Apeks        Team Liquid
                  1          G2 Esports               ENCE              Monte
                  2                9INE      Natus Vincere             HEROIC
                  3       FURIA Esports             Fnatic      Team Vitality
                  4       Natus Vincere               9INE             Fnatic
                  5     Into The Breach             HEROIC    Bad News Eagles
                  6               Apeks          FaZe Clan               ENCE
                  7              HEROIC    Into The Breach               9INE
                  8         GamerLegion        Team Liquid  Ninjas in Pyjamas
                  9   Ninjas in Pyjamas              Monte        GamerLegion
                  10             Fnatic      FURIA Esports      Natus Vincere
                  11    Bad News Eagles      Team Vitality    Into The Breach
                  12               ENCE         G2 Esports              Apeks
                  13      Team Vitality    Bad News Eagles      FURIA Esports
                  14        Team Liquid        GamerLegion          FaZe Clan
                  15              Monte  Ninjas in Pyjamas         G2 Esports
Playoff Stage     0     Into The Breach              Apeks        GamerLegion
                  1               Monte             Heroic      Team Vitality
                  2           FaZe Clan        GamerLegion
                  3         Team Liquid      Team Vitality
                  4              Heroic
                  5         GamerLegion
                  6               Apeks
                  7       Team Vitality

                                Round 4            Round 5
Opening Stage     0
                  1
                  2         paiN Gaming
                  3       FORZE Esports
                  4    Grayhound Gaming
                  5         The MongolZ        paiN Gaming
                  6   Complexity Gaming   Grayhound Gaming
                  7                  OG      FORZE Esports
                  8           FaZe Clan        GamerLegion
                  9   Ninjas in Pyjamas        Team Liquid
                  10              Apeks              Monte
                  11        Team Liquid
                  12              Monte
                  13        GamerLegion
                  14
                  15
Elimination Stage 0
                  1
                  2     Into The Breach
                  3       Natus Vincere
                  4               Apeks
                  5         GamerLegion  Ninjas in Pyjamas
                  6         Team Liquid             Fnatic
                  7     Bad News Eagles      Natus Vincere
                  8               Monte          FaZe Clan
                  9          G2 Esports    Into The Breach
                  10               ENCE              Apeks
                  11  Ninjas in Pyjamas
                  12          FaZe Clan
                  13             Fnatic
                  14
                  15
Playoff Stage     0
                  1
                  2
                  3
                  4
                  5
                  6
                  7

***2022 Data Frame***

In [ ]:
# df_22 = pd.concat([df_o, df_e, df_p2], keys=['Opening Stage', 'Elimination Stage', 'Playoff Stage'])
# path = r"C:\Languages\python\PFAI\Project\2022.csv"
# df_22.to_csv(path)
# df_22

                                   Team Matches   Rounds   RD  \
Opening Stage     0          G2 Esports     3-0    83-58  +25
                  1       Team Vitality     3-0    76-46  +30
                  2                ENCE     3-1    99-83  +16
                  3         Team Spirit     3-1    81-54  +27
                  4           Outsiders     3-1    82-76   +6
                  5    Imperial Esports     3-2   109-90  +19
                  6     Bad News Eagles     3-2  106-108   -2
                  7         Team Liquid     3-2  112-105   +7
                  8       FORZE Esports     2-3  116-136  -20
                  9            Astralis     2-3    85-95  -10
                  10               MIBR     2-3  109-115   -6
                  11  Complexity Gaming     1-3    50-77  -27
                  12       Eternal Fire     1-3    65-66   -1
                  13        IHC Esports     1-3    85-97  -12
                  14            9z Team     0-3    43-64  -21
                  15          Renegades     0-3    33-64  -31
Elimination Stage 0         Team Spirit     3-0    74-54  +20
                  1       Natus Vincere     3-0    81-51  +30
                  2                ENCE     3-1    86-66  +20
                  3   Ninjas in Pyjamas     3-1    90-76  +14
                  4           FaZe Clan     3-1    85-63  +22
                  5   Copenhagen Flames     3-2  135-129   +6
                  6              HEROIC     3-2  127-125   +2
                  7       FURIA Esports     3-2  102-106   -4
                  8          G2 Esports     2-3  131-133   -2
                  9       Team Vitality     2-3  133-144  -11
                  10   Imperial Esports     2-3  125-139  -14
                  11                BIG     1-3    82-97  -15
                  12             Cloud9     1-3    80-94  -14
                  13          Outsiders     1-3    73-82   -9
                  14    Bad News Eagles     0-3    45-64  -19
                  15        Team Liquid     0-3    38-64  -26
Playoff Stage     0           FaZe Clan     3-0   121-96   25
                  1       Natus Vincere     2-1   100-92    8
                  2         Team Spirit     1-1    72-61   11
                  3                ENCE     1-1    51-54   -3
                  4       FURIA Esports     0-1    20-32  -12
                  5   Ninjas in Pyjamas     0-1    34-45  -11
                  6          CPH Flames     0-1    22-32  -10
                  7              Heroic     0-1    38-42   -4

                                Round 1            Round 2            Round 3  \
Opening Stage     0         Team Liquid        Team Spirit               ENCE
                  1   Complexity Gaming           Astralis      FORZE Esports
                  2             9z Team          Outsiders         G2 Esports
                  3    Imperial Esports         G2 Esports       Eternal Fire
                  4                MIBR               ENCE  Complexity Gaming
                  5         Team Spirit        Team Liquid    Bad News Eagles
                  6        Eternal Fire      FORZE Esports   Imperial Esports
                  7          G2 Esports   Imperial Esports            9z Team
                  8           Renegades    Bad News Eagles      Team Vitality
                  9         IHC Esports      Team Vitality               MIBR
                  10          Outsiders            9z Team           Astralis
                  11      Team Vitality        IHC Esports          Outsiders
                  12    Bad News Eagles          Renegades        Team Spirit
                  13           Astralis  Complexity Gaming          Renegades
                  14               ENCE               MIBR        Team Liquid
                  15      FORZE Esports       Eternal Fire        IHC Esports
Elimination Stage 0       FURIA Esports             HEROIC  Copenhagen Flames
                  1          G2 Esports                BIG  Ninjas in Pyjamas
                  2           FaZe Clan  Copenhagen Flames          Outsiders
                  3       Team Vitality             Cloud9      Natus Vincere
                  4                ENCE    Bad News Eagles             Cloud9
                  5     Bad News Eagles               ENCE        Team Spirit
                  6         Team Liquid        Team Spirit         G2 Esports
                  7         Team Spirit        Team Liquid                BIG
                  8       Natus Vincere   Imperial Esports             HEROIC
                  9   Ninjas in Pyjamas          Outsiders        Team Liquid
                  10                BIG         G2 Esports    Bad News Eagles
                  11   Imperial Esports      Natus Vincere      FURIA Esports
                  12          Outsiders  Ninjas in Pyjamas          FaZe Clan
                  13             Cloud9      Team Vitality               ENCE
                  14  Copenhagen Flames          FaZe Clan   Imperial Esports
                  15             HEROIC      FURIA Esports      Team Vitality
Playoff Stage     0   Ninjas in Pyjamas        Team Spirit      Natus Vincere
                  1              Heroic               ENCE          FaZe Clan
                  2       FURIA Esports          FaZe Clan
                  3          CPH Flames      Natus Vincere
                  4         Team Spirit
                  5           FaZe Clan
                  6                ENCE
                  7       Natus Vincere

                                Round 4            Round 5
Opening Stage     0
                  1
                  2     Bad News Eagles
                  3            Astralis
                  4       FORZE Esports
                  5         IHC Esports      FORZE Esports
                  6                ENCE               MIBR
                  7   Complexity Gaming           Astralis
                  8           Outsiders   Imperial Esports
                  9         Team Spirit        Team Liquid
                  10       Eternal Fire    Bad News Eagles
                  11        Team Liquid
                  12               MIBR
                  13   Imperial Esports
                  14
                  15
Elimination Stage 0
                  1
                  2              HEROIC
                  3       FURIA Esports
                  4   Copenhagen Flames
                  5           FaZe Clan   Imperial Esports
                  6                ENCE      Team Vitality
                  7   Ninjas in Pyjamas         G2 Esports
                  8           Outsiders      FURIA Esports
                  9                 BIG             HEROIC
                  10             Cloud9  Copenhagen Flames
                  11      Team Vitality
                  12   Imperial Esports
                  13         G2 Esports
                  14
                  15
Playoff Stage     0
                  1
                  2
                  3
                  4
                  5
                  6
                  7

***2021 Data Frame***

In [ ]:
# df_21 = pd.concat([df_o, df_e, df_p1], keys=['Opening Stage', 'Elimination Stage', 'Playoff Stage'])
# path = r"C:\Languages\python\PFAI\Project\2021.csv"
# df_21.to_csv(path)
# df_21

                                   Team Matches   Rounds   RD  \
Opening Stage     0           FaZe Clan     3-0    64-43  +21
                  1   Copenhagen Flames     3-0    75-52  +23
                  2                ENCE     3-1    86-71  +15
                  3            Entropiq     3-1    87-68  +19
                  4          Virtus.pro     3-1    99-96   +3
                  5              HEROIC     3-2  133-129   +4
                  6            Astralis     3-2   111-90  +21
                  7                MOUZ     3-2  126-110  +16
                  8                 BIG     2-3  117-122   -5
                  9         Team Spirit     2-3  101-110   -9
                  10    Movistar Riders     2-3  103-123  -20
                  11        paiN Gaming     1-3  106-110   -4
                  12          Renegades     1-3    70-92  -22
                  13              TYLOO     1-3    77-88  -11
                  14            GODSENT     0-3    36-64  -28
                  15     Sharks Esports     0-3    63-86  -23
Elimination Stage 0       Natus Vincere     3-0    64-33  +31
                  1          G2 Esports     3-0    64-40  +24
                  2              HEROIC     3-1    88-66  +22
                  3      Gambit Esports     3-1    73-56  +17
                  4       FURIA Esports     3-1    82-68  +14
                  5          Virtus.pro     3-2  126-124   +2
                  6   Ninjas in Pyjamas     3-2  114-123   -9
                  7       Team Vitality     3-2  162-139  +23
                  8            Entropiq     2-3  123-135  -12
                  9   Copenhagen Flames     2-3  120-114   +6
                  10          FaZe Clan     2-3  108-110   -2
                  11           Astralis     1-3    63-88  -25
                  12               MOUZ     1-3    90-95   -5
                  13        Team Liquid     1-3    61-78  -17
                  14      Evil Geniuses     0-3    41-77  -36
                  15               ENCE     0-3    31-64  -33
Playoff Stage     0       Natus Vincere     3-0   102-65   37
                  1          G2 Esports     2-1  109-101    8
                  2      Gambit Esports     1-1    46-59  -13
                  3              Heroic     1-1    86-85    1
                  4       Team Vitality     0-1    24-32   -8
                  5       FURIA Esports     0-1    27-35   -8
                  6          Virtus.pro     0-1    38-45   -7
                  7   Ninjas in Pyjamas     0-1    22-32  -10

                                Round 1            Round 2            Round 3  \
Opening Stage     0         Team Spirit               ENCE         Virtus.pro
                  1            Astralis                BIG             HEROIC
                  2             GODSENT          FaZe Clan               MOUZ
                  3                 BIG           Astralis    Movistar Riders
                  4         paiN Gaming    Movistar Riders          FaZe Clan
                  5               TYLOO               MOUZ  Copenhagen Flames
                  6   Copenhagen Flames           Entropiq            GODSENT
                  7      Sharks Esports             HEROIC               ENCE
                  8            Entropiq  Copenhagen Flames          Renegades
                  9           FaZe Clan            GODSENT              TYLOO
                  10          Renegades         Virtus.pro           Entropiq
                  11         Virtus.pro          Renegades     Sharks Esports
                  12    Movistar Riders        paiN Gaming                BIG
                  13             HEROIC     Sharks Esports        Team Spirit
                  14               ENCE        Team Spirit           Astralis
                  15               MOUZ              TYLOO        paiN Gaming
Elimination Stage 0              HEROIC         Virtus.pro  Ninjas in Pyjamas
                  1   Copenhagen Flames          FaZe Clan           Entropiq
                  2       Natus Vincere      Team Vitality           Astralis
                  3                ENCE           Entropiq         Virtus.pro
                  4            Astralis               MOUZ        Team Liquid
                  5       Team Vitality      Natus Vincere     Gambit Esports
                  6                MOUZ           Astralis      Natus Vincere
                  7          Virtus.pro             HEROIC      Evil Geniuses
                  8         Team Liquid     Gambit Esports         G2 Esports
                  9          G2 Esports      Evil Geniuses          FaZe Clan
                  10      Evil Geniuses         G2 Esports  Copenhagen Flames
                  11      FURIA Esports  Ninjas in Pyjamas             HEROIC
                  12  Ninjas in Pyjamas      FURIA Esports               ENCE
                  13           Entropiq               ENCE      FURIA Esports
                  14          FaZe Clan  Copenhagen Flames      Team Vitality
                  15     Gambit Esports        Team Liquid               MOUZ
Playoff Stage     0       Team Vitality     Gambit Esports         G2 Esports
                  1   Ninjas in Pyjamas             Heroic      Natus Vincere
                  2       FURIA Esports      Natus Vincere
                  3          Virtus.pro         G2 Esports
                  4       Natus Vincere
                  5      Gambit Esports
                  6              Heroic
                  7          G2 Esports

                                Round 4            Round 5
Opening Stage     0
                  1
                  2                 BIG
                  3              HEROIC
                  4         Team Spirit
                  5            Entropiq    Movistar Riders
                  6         paiN Gaming        Team Spirit
                  7           Renegades                BIG
                  8                ENCE               MOUZ
                  9          Virtus.pro           Astralis
                  10              TYLOO             HEROIC
                  11           Astralis
                  12               MOUZ
                  13    Movistar Riders
                  14
                  15
Elimination Stage 0
                  1
                  2   Copenhagen Flames
                  3   Ninjas in Pyjamas
                  4            Entropiq
                  5                MOUZ          FaZe Clan
                  6      Gambit Esports  Copenhagen Flames
                  7            Astralis           Entropiq
                  8       FURIA Esports      Team Vitality
                  9              HEROIC  Ninjas in Pyjamas
                  10        Team Liquid         Virtus.pro
                  11      Team Vitality
                  12         Virtus.pro
                  13          FaZe Clan
                  14
                  15
Playoff Stage     0
                  1
                  2
                  3
                  4
                  5
                  6
                  7